USE [master]
GO

/****** Object:  Database [License_Portal]    Script Date: 02-09-2021 16:22:55 ******/
DROP DATABASE [License_Portal]
GO

/****** Object:  Database [License_Portal]    Script Date: 02-09-2021 16:22:55 ******/
CREATE DATABASE [License_Portal]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'License_Portal', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\License_Portal.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'License_Portal_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\License_Portal_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [License_Portal].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [License_Portal] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [License_Portal] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [License_Portal] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [License_Portal] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [License_Portal] SET ARITHABORT OFF 
GO

ALTER DATABASE [License_Portal] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [License_Portal] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [License_Portal] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [License_Portal] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [License_Portal] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [License_Portal] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [License_Portal] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [License_Portal] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [License_Portal] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [License_Portal] SET  DISABLE_BROKER 
GO

ALTER DATABASE [License_Portal] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [License_Portal] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [License_Portal] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [License_Portal] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [License_Portal] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [License_Portal] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [License_Portal] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [License_Portal] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [License_Portal] SET  MULTI_USER 
GO

ALTER DATABASE [License_Portal] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [License_Portal] SET DB_CHAINING OFF 
GO

ALTER DATABASE [License_Portal] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [License_Portal] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [License_Portal] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [License_Portal] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [License_Portal] SET QUERY_STORE = OFF
GO

ALTER DATABASE [License_Portal] SET  READ_WRITE 
GO


